import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {FaReact} from 'react-icons/fa'
import {AifillTwitterCircle, AiFillLinkedin, AiFillGithub, AiFillTwitterCircle} from 'react-icons/ai'
import Image from 'next/image'
import devgib from '../../public/dev-gib.png'
import design from '../../public/design.png'
import code from '../../public/design.png'
import consulting from '../../public/design.png'
import web1 from "../../public/web1.png"
import web2 from "../../public/web2.png"
import web3 from "../../public/web3.png"
import web4 from "../../public/web4.png"
import web5 from "../../public/web5.png"
import web6 from "../../public/web6.png"
import { useState } from 'react'
import { motion } from "framer-motion"









export default function Home() {
  const [darkMode, setDarkMode] = useState(false)
  
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Brian Giblin's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40'>
        <section className='min-h-screen'>
        <nav className='py-10 mb-12 flex justify-between'>
          <h1 className='text-xl font-burtons' >BGWEBDESIGNS</h1>
          <ul className='flex items-center'>
            <li>
              <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl' />
              

            </li>
            <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='#'>Resume</a></li>
           
          </ul>
        </nav>
        <div className='text-center py-10'>
          <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl max-w-xl mx-auto'>Brian Giblin</h2>
          <h3 className='text-2xl py-2 md:text-3xl'>React developer and designer.</h3>
          <p className='text-md leading-8 text-gray-800 py-4 md:text-xl max-w-xl mx-auto'>
            Freelancer providing services for for all of your web development needs. Through exceptional communication I will develop a product specially tailored to your liking.   Join me below and lets get started. 
          </p>
        </div>
        <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
          <a href='#'><AiFillTwitterCircle/></a>
          <a href='#'><AiFillLinkedin/></a>
          <a href='#'><AiFillGithub/></a>
        </div>
        <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 md:h-96 md:w-96'>
          <Image 
          src={devgib} 
          alt='portrait'
          fill
          style={{ojectFit:'cover'}}
            />
    
        </div>
        </section>
        {/* second page */}
        <section>
          <div>
            <h3 className='text-3xl py-1'>
              Services I Offer
            </h3>
            <p className='text-md py-2 leading-8'>Since the beginning of my journey as freelance <span className='text-teal-500'>designer</span> and <span className='text-teal-500'>developer</span>, I've been honing in on indusrty standard practices in order to build business and consumer based projects.  </p>
            <p className='text-md py-2 leading-8 text-gray-800'>
              I offer a wide range of services including design and development of your business or personal website.
            </p>  
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-2xl p-10 my-10'>
              <Image src={design} width={100} height={100} alt='Design logo' className='mx-auto'/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Alluring Designs</h3>
              <p className='py-2'>
                Creating elegant designs suited for your needs following the most contemporary practices. 
              </p>
              <h4 className='py-4 text-teal-500'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>figma</p>
              <p className='text-gray-800 py-1'></p>
              <p className='text-gray-800 py-1'></p>
              
            </div>
          
          <div>
            <div className='text-center shadow-2xl p-10 my-10'>
              <Image src={consulting} width={100} height={100} alt='Design logo' className='mx-auto'/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Development</h3>
              <p className='py-2'>
                Creating elegant designs suited for your needs following the most contemporary practices. 
              </p>
              <h4 className='py-4 text-teal-500'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>figma</p>
              <p className='text-gray-800 py-1'></p>
              <p className='text-gray-800 py-1'></p>
              
            </div>
          </div>
          <div>
            <div className='text-center shadow-2xl p-10 my-10'>
              <Image src={code} width={100} height={100} alt='Design logo' className='mx-auto'/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Alluring Designs</h3>
              <p className='py-2'>
                Creating elegant designs suited for your needs following the most contemporary practices. 
              </p>
              <h4 className='py-4 text-teal-500'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>figma</p>
              <p className='text-gray-800 py-1'></p>
              <p className='text-gray-800 py-1'></p>
              
            </div>
          </div>
          </div>
        </section>
        {/* portfolio page */}
        <section>
          <div>
            <h3 className='text-3xl py-1'>
              Portfolio
            </h3>
            <p className='text-md py-2 leading-8'>Since the beginning of my journey as freelance <span className='text-teal-500'>designer</span> and <span className='text-teal-500'>developer</span>, I've been honing in on indusrty standard practices in order to build business and consumer based projects.  </p>
            <p className='text-md py-2 leading-8 text-gray-800'>
              I offer a wide range of services including design and development of your business or personal website.
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <div><Image src={web1} className="rounded-lg object-cover" alt='' width={'100%'} responsive/></div>
            </div>
            <div className='basis-1/3 flex-1'>
              <div><Image src={web2} className="rounded-lg object-cover" alt='' width={'100%'} responsive/></div>
            </div>
            <div className='basis-1/3 flex-1'>
              <div><Image src={web3} className="rounded-lg object-cover" alt='' width={'100%'} responsive/></div>
            </div>
            <div className='basis-1/3 flex-1'>
              <div><Image src={web4} className="rounded-lg object-cover" alt='' width={'100%'} responsive/></div>
            </div>
            <div className='basis-1/3 flex-1'>
              <div><Image src={web5} className="rounded-lg object-cover" alt='' width={'100%'} responsive/></div>
            </div>
            <div className='basis-1/3 flex-1'>
              <div><Image src={web6} className="rounded-lg object-cover" alt='' width={'100%'} responsive/></div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
